# Generated by Django 4.0.2 on 2025-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('E', 'Elf'), ('D', 'Dwarf'), ('H', 'Human'), ('O', 'Ork')], max_length=255, unique=True),
        ),
    ]
