# Generated by Django 4.0.2 on 2023-10-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='guild',
            new_name='guild_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='race',
            new_name='race_id',
        ),
    ]
