# Generated by Django 5.1.7 on 2025-03-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="db.guild",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="db.race",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="db.race",
            ),
        ),
    ]
