# Generated by Django 4.0.2 on 2023-10-16 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bonus', models.CharField(max_length=255, verbose_name='Describes what kind of bonus players can get from it.')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='db.rase')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('bio', models.CharField(max_length=255, verbose_name='It stores a short description provided by a user about himself/herself.')),
                ('created_at', models.DateTimeField(default=datetime.date(2023, 10, 16))),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='db.guild')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='db.rase')),
            ],
        ),
    ]
