# Generated by Django 4.0.2 on 2024-03-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='racer',
            new_name='race',
        ),
    ]
