# Generated by Django 4.0.2 on 2025-02-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='definition',
            new_name='description',
        ),
    ]
