# Generated by Django 4.0.2 on 2024-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, choices=[('Elf', 'ELF'), ('Dwarf', 'DWARF'), ('Human', 'HUMAN'), ('Ork', 'ORK')]),
        ),
    ]
