# Generated by Django 4.0.2 on 2025-01-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.race'),
        ),
    ]
