# Generated by Django 4.0.2 on 2022-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255, verbose_name='Describes what kind of bonus players can get'),
        ),
    ]
