# Generated by Django 4.0.2 on 2024-04-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'Elf race'), ('Dwarf', 'Dwarf race'), ('Human', 'Human race'), ('Ork', 'Ork race')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.race'),
        ),
    ]
