# Generated by Django 4.0.2 on 2024-11-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
