# Generated by Django 4.2.1 on 2023-06-05 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="nickname",
        ),
    ]
