# Generated by Django 4.0.2 on 2023-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255, verbose_name='Short description provided by a user about himself'),
        ),
    ]
