# Generated by Django 4.0.2 on 2024-07-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerModel',
            new_name='Player',
        ),
    ]
