# Generated by Django 4.0.2 on 2022-11-10 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 12, 42, 8, 318096)),
        ),
    ]
