# Generated by Django 4.0.2 on 2024-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='guilds', to='db.Player'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
