# Generated by Django 4.0.2 on 2024-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='email',
        ),
    ]
