# Generated by Django 4.0.2 on 2023-11-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bonus',
            new_name='email',
        ),
    ]
