# Generated by Django 4.0.2 on 2023-03-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('elf', None), ('dwarf', None), ('human', None), ('ork', None)], max_length=255, unique=True),
        ),
    ]
