# Generated by Django 4.0.2 on 2024-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='races',
            field=models.ManyToManyField(related_name='skill_set', to='db.Race'),
        ),
    ]
