# Generated by Django 4.0.2 on 2022-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='rase',
            new_name='race',
        ),
    ]
