# Generated by Django 4.0.2 on 2022-06-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='guilde',
            new_name='guild',
        ),
    ]
