# Generated by Django 4.2.6 on 2023-11-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.race"
            ),
        ),
    ]
