# Generated by Django 4.0.2 on 2025-03-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(related_name='players', to='db.Skill'),
        ),
    ]
