# Generated by Django 4.0.2 on 2024-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(choices=[['elf', ''], ['dwarf', ''], ['human', ''], ['ork', '']], max_length=5),
        ),
    ]
