# Generated by Django 4.0.2 on 2024-07-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_model',
            new_name='PlayerModel',
        ),
    ]
