# Generated by Django 4.0.2 on 2023-09-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.guild",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="skill",
            name="bonus",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
