# Generated by Django 4.0.2 on 2024-08-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='rase',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='rase',
            new_name='race',
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.guild'),
        ),
    ]
