# Generated by Django 4.0.2 on 2024-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='rece',
            new_name='race',
        ),
    ]
