# Generated by Django 4.0.4 on 2022-10-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='db.guild'),
            preserve_default=False,
        ),
    ]
