# Generated by Django 4.0.2 on 2025-01-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[(1, 'Elf'), (2, 'Dwarf'), (3, 'Human'), (4, 'Ork')], max_length=255, unique=True),
        ),
    ]
