# Generated by Django 4.0.2 on 2023-10-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_guild_player_guild_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='guild_id',
            new_name='guild',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='race_id',
            new_name='race',
        ),
    ]
