# Generated by Django 4.0.2 on 2025-01-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='nam',
            new_name='name',
        ),
    ]
