# Generated by Django 4.0.2 on 2023-03-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_guild_race_description_alter_race_name_skill_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Race',
            new_name='Race1',
        ),
    ]
