# Generated by Django 4.0.2 on 2024-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_race_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'The magic race'), ('Dwarf', 'DWARF'), ('Human', 'HUMAN'), ('Ork', 'ORK')], max_length=255),
        ),
    ]
