# Generated by Django 4.0.2 on 2023-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bonus',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
