# Generated by Django 4.1 on 2024-08-29 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_player_email_alter_player_guild_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_set",
                to="db.race",
            ),
        ),
    ]
