# Generated by Django 4.0.2 on 2023-09-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_skill_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.race"
            ),
        ),
    ]
