# Generated by Django 4.0.2 on 2024-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_player_email_alter_player_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(related_name='players', to='db.Skill'),
        ),
    ]
