# Generated by Django 4.0.2 on 2022-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255, null=True, verbose_name='This field describes what kind of bonus players can get from it.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
