# Generated by Django 4.0.2 on 2023-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
