# Generated by Django 4.0.2 on 2024-12-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_skill_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='races',
            new_name='race',
        ),
    ]
