# Generated by Django 4.0.2 on 2023-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_player_guild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="guild",
        ),
        migrations.RemoveField(
            model_name="player",
            name="race",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="race",
        ),
        migrations.DeleteModel(
            name="Guild",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.DeleteModel(
            name="Race",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
