# Generated by Django 4.0.2 on 2024-03-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_race_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='race',
        ),
    ]
