# Generated by Django 4.0.2 on 2024-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_player_rename_descriptions_guild_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(related_name='players', to='db.Skill'),
        ),
    ]
