# Generated by Django 5.0.4 on 2024-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_race_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="name",
            field=models.CharField(
                choices=[
                    ("elf", "Elf"),
                    ("dwarf", "Dwarf"),
                    ("human", "Human"),
                    ("ork", "Ork"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
