# Generated by Django 4.0.2 on 2024-02-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_playermodel_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255, verbose_name='It stores a short description provided by a user about himself/herself.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255, verbose_name='This field describes what kind of bonus players can get from it.'),
        ),
    ]
