# Generated by Django 4.0.2 on 2024-07-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_guild_description_alter_skill_race'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prayer',
            new_name='Player',
        ),
    ]
