# Generated by Django 4.0.2 on 2024-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_name_player_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='race',
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('elf', 'elf'), ('dwarf', 'dwarf'), ('human', 'human'), ('ork', 'ork')], max_length=255, unique=True),
        ),
    ]
