# Generated by Django 4.0.2 on 2022-07-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.guild'),
        ),
    ]
