# Generated by Django 4.0.2 on 2022-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_playermodel_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='description',
        ),
        migrations.AddField(
            model_name='guild',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
