# Generated by Django 4.0.2 on 2023-09-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_skill_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bonus',
        ),
    ]
