# Generated by Django 4.0.2 on 2024-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_guild_description_alter_race_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
