# Generated by Django 4.0.2 on 2024-08-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race',
            new_name='name',
        ),
    ]
