# Generated by Django 4.0.2 on 2024-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_players_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='desription',
            new_name='desсription',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='desription',
            new_name='desсription',
        ),
    ]
