# Generated by Django 4.0.2 on 2024-06-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_playermodel_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='db.guild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='db.race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='bonus',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.race'),
            preserve_default=False,
        ),
    ]
