# Generated by Django 4.0.2 on 2023-10-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='choose_roles',
        ),
    ]
