# Generated by Django 4.0.2 on 2024-06-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_race_race_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.guild'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('elf', 'Elves. Race of woods'), ('dwarf', 'Dwarves. Race of blacksmiths, lives under the mountains'), ('human', 'Humans are just humans'), ('ork', 'Orks. Race of filth and misery')], max_length=255, unique=True),
        ),
    ]
