# Generated by Django 4.0.2 on 2023-09-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_guild_name_alter_skill_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.guild"
            ),
        ),
    ]
