# Generated by Django 4.0.2 on 2023-10-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rase',
            new_name='Race',
        ),
    ]
