# Generated by Django 4.0.2 on 2025-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('elf', 'elf'), ('dwarf', 'dwarf'), ('human', 'human'), ('ork', 'ork')], max_length=255, unique=True),
        ),
    ]
