# Generated by Django 4.0.2 on 2024-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_bio_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255),
        ),
    ]
