# Generated by Django 4.0.2 on 2024-04-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_desription_guild_desсription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='desсription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='desсription',
            new_name='description',
        ),
    ]
