# Generated by Django 4.0.2 on 2022-11-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_guild_description_guild_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='descriptions',
            new_name='description',
        ),
    ]
