# Generated by Django 4.0.2 on 2025-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
