# Generated by Django 4.0.2 on 2024-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_name_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
