# Generated by Django 4.0.2 on 2025-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_guild_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
