# Generated by Django 5.0.4 on 2024-04-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_race_name_alter_skill_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="guild",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.guild"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.race"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="race",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="db.race"
            ),
        ),
    ]
