# Generated by Django 4.0.2 on 2024-01-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_guild_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
    ]
