# Generated by Django 4.0.2 on 2023-03-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_race_race1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Race1',
            new_name='Race',
        ),
    ]
