# Generated by Django 4.0.2 on 2025-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_guild_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
