# Generated by Django 5.1.2 on 2024-10-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_skill_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nickname',
        ),
    ]
