# Generated by Django 4.0.2 on 2023-09-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_alter_player_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bio",
            field=models.CharField(max_length=255),
        ),
    ]
