# Generated by Django 4.0.2 on 2022-11-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_descriptions_guild_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
