# Generated by Django 4.0.2 on 2024-05-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
