# Generated by Django 4.0.2 on 2025-03-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_guild_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
