# Generated by Django 4.0.2 on 2024-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_player_created_at_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'Elf'), ('Human', 'Human'), ('Dwarf', 'Dwarf'), ('Orc', 'Orc')], max_length=255, unique=True),
        ),
    ]
