# Generated by Django 4.0.2 on 2025-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_guild_description_alter_skill_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
