# Generated by Django 4.0.2 on 2022-09-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_skill_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='race',
        ),
    ]
