# Generated by Django 4.1 on 2024-08-29 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_player_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="race",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="db.race",
            ),
        ),
    ]
