# Generated by Django 5.1.4 on 2024-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_skill_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
