# Generated by Django 4.0.2 on 2024-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_guild_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('ELF', 'Elf'), ('DWARF', 'Dwarf'), ('ORK', 'Ork'), ('HUMAN', 'Human')], max_length=255, unique=True),
        ),
    ]
