# Generated by Django 5.1.2 on 2024-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_name_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
