# Generated by Django 4.0.2 on 2024-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
