# Generated by Django 4.0.2 on 2022-10-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_player_guild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
