# Generated by Django 4.0.2 on 2025-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_skill_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
