# Generated by Django 4.0.2 on 2025-02-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_player_guild_alter_player_race_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='created',
            new_name='created_at',
        ),
    ]
