# Generated by Django 4.0.2 on 2025-02-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_guild_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.ForeignKey(default='Human', on_delete=django.db.models.deletion.CASCADE, to='db.race'),
        ),
    ]
