# Generated by Django 4.0.2 on 2023-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_skill_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255, verbose_name='Describes what kind of bonusplayers can get from it.'),
        ),
    ]
