# Generated by Django 4.0.2 on 2022-12-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_player_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255, verbose_name='It stores a short description provided by a user about himself/herself.'),
        ),
    ]
