# Generated by Django 4.0.2 on 2025-02-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_player_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.ForeignKey(default='Elf', on_delete=django.db.models.deletion.CASCADE, to='db.race'),
        ),
    ]
