# Generated by Django 4.0.2 on 2025-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_guild_name_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(default='NoDescription', null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default='NoName', max_length=255, null=True, unique=True),
        ),
    ]
